services:
  frontend:
    build: .
    container_name: banka2_frontend
    ports:
      - "3000:80"
    networks:
      - banka2_net

networks:
  banka2_net:
    external: true
    name: banka-2-backend_default
